// Sector map from Stocks_Final.ipynb cell 12 (verbatim, quirks preserved).
export const NB_SECTOR_MAP: Record<string, string> = {
  "HDFCBANK.NS": "Banking",
  "ICICIBANK.NS": "Banking",
  "SBIN.NS": "Banking",
  "AXISBANK.NS": "Banking",
  "KOTAKBANK.NS": "Banking",
  "BANKBARODA.NS": "Banking",
  "CANBK.NS": "Banking",
  "PNB.NS": "Banking",
  "UNIONBANK.NS": "Banking",
  "INDIANB.NS": "Banking",
  "BANKINDIA.NS": "Banking",
  "FEDERALBNK.NS": "Banking",
  "YESBANK.NS": "Banking",
  "RBLBANK.NS": "Banking",
  "IDFCFIRSTB.NS": "Banking",
  "INDUSINDBK.NS": "Banking",
  "BANDHANBNK.NS": "Banking",
  "AUBANK.NS": "Banking",
  "BAJFINANCE.NS": "NBFC & Fin Services",
  "BAJAJFINSV.NS": "NBFC & Fin Services",
  "SHRIRAMFIN.NS": "NBFC & Fin Services",
  "CHOLAFIN.NS": "NBFC & Fin Services",
  "MUTHOOTFIN.NS": "NBFC & Fin Services",
  "MANAPPURAM.NS": "NBFC & Fin Services",
  "ABCAPITAL.NS": "NBFC & Fin Services",
  "LTF.NS": "NBFC & Fin Services",
  "LICHSGFIN.NS": "NBFC & Fin Services",
  "PNBHOUSING.NS": "NBFC & Fin Services",
  "JIOFIN.NS": "NBFC & Fin Services",
  "SAMMAANCAP.NS": "NBFC & Fin Services",
  "HDFCLIFE.NS": "Insurance",
  "SBILIFE.NS": "Insurance",
  "LICI.NS": "Insurance",
  "ICICIGI.NS": "Insurance",
  "ICICIPRULI.NS": "Insurance",
  "MAXHEALTH.NS": "Insurance",
  "MFSL.NS": "Insurance",
  "POLICYBZR.NS": "Insurance",
  "BSE.NS": "Capital Markets",
  "MCX.NS": "Capital Markets",
  "CDSL.NS": "Capital Markets",
  "ANGELONE.NS": "Capital Markets",
  "HDFCAMC.NS": "Capital Markets",
  "NAM-INDIA.NS": "Capital Markets",
  "MOTILALOFS.NS": "Capital Markets",
  "NUVAMA.NS": "Capital Markets",
  "360ONE.NS": "Capital Markets",
  "KFINTECH.NS": "Capital Markets",
  "CAMS.NS": "Capital Markets",
  "IEX.NS": "Capital Markets",
  "BAJAJHLDNG.NS": "Capital Markets",
  "INFY.NS": "IT & Technology",
  "TCS.NS": "IT & Technology",
  "HCLTECH.NS": "IT & Technology",
  "WIPRO.NS": "IT & Technology",
  "TECHM.NS": "IT & Technology",
  "COFORGE.NS": "IT & Technology",
  "PERSISTENT.NS": "IT & Technology",
  "MPHASIS.NS": "IT & Technology",
  "KPITTECH.NS": "IT & Technology",
  "TATAELXSI.NS": "IT & Technology",
  "OFSS.NS": "IT & Technology",
  "NAUKRI.NS": "IT & Technology",
  "PAYTM.NS": "IT & Technology",
  "NYKAA.NS": "IT & Technology",
  "DELHIVERY.NS": "IT & Technology",
  "SWIGGY.NS": "IT & Technology",
  "BHARTIARTL.NS": "Telecom",
  "IDEA.NS": "Telecom",
  "INDUSTOWER.NS": "Telecom",
  "RELIANCE.NS": "Oil Gas & Petrochem",
  "ONGC.NS": "Oil Gas & Petrochem",
  "OIL.NS": "Oil Gas & Petrochem",
  "BPCL.NS": "Oil Gas & Petrochem",
  "HINDPETRO.NS": "Oil Gas & Petrochem",
  "IOC.NS": "Oil Gas & Petrochem",
  "GAIL.NS": "Oil Gas & Petrochem",
  "PETRONET.NS": "Oil Gas & Petrochem",
  "TATASTEEL.NS": "Metals & Mining",
  "JSWSTEEL.NS": "Metals & Mining",
  "HINDALCO.NS": "Metals & Mining",
  "VEDL.NS": "Metals & Mining",
  "SAIL.NS": "Metals & Mining",
  "NMDC.NS": "Metals & Mining",
  "NATIONALUM.NS": "Metals & Mining",
  "HINDZINC.NS": "Metals & Mining",
  "COALINDIA.NS": "Metals & Mining",
  "APLAPOLLO.NS": "Metals & Mining",
  "JINDALSTEL.NS": "Metals & Mining",
  "ADANIPOWER.NS": "Power & Renewables",
  "ADANIGREEN.NS": "Power & Renewables",
  "ADANIENSOL.NS": "Power & Renewables",
  "TATAPOWER.NS": "Power & Renewables",
  "NTPC.NS": "Power & Renewables",
  "POWERGRID.NS": "Power & Renewables",
  "POWERINDIA.NS": "Power & Renewables",
  "NHPC.NS": "Power & Renewables",
  "JSWENERGY.NS": "Power & Renewables",
  "IREDA.NS": "Power & Renewables",
  "SUZLON.NS": "Power & Renewables",
  "WAAREEENER.NS": "Power & Renewables",
  "INOXWIND.NS": "Power & Renewables",
  "PREMIERENE.NS": "Power & Renewables",
  "SOLARINDS.NS": "Power & Renewables",
  "LT.NS": "Infra & Construction",
  "ADANIPORTS.NS": "Infra & Construction",
  "ADANIENT.NS": "Infra & Construction",
  "RVNL.NS": "Infra & Construction",
  "NBCC.NS": "Infra & Construction",
  "IRFC.NS": "Infra & Construction",
  "PFC.NS": "Infra & Construction",
  "RECLTD.NS": "Infra & Construction",
  "GMRAIRPORT.NS": "Infra & Construction",
  "CONCOR.NS": "Infra & Construction",
  "HAL.NS": "Defence & Aerospace",
  "BEL.NS": "Defence & Aerospace",
  "BHEL.NS": "Defence & Aerospace",
  "MAZDOCK.NS": "Defence & Aerospace",
  "COCHINSHIP.NS": "Defence & Aerospace",
  "BDL.NS": "Defence & Aerospace",
  "TIINDIA.NS": "Defence & Aerospace",
  "CIPLA.NS": "Pharma & Healthcare",
  "SUNPHARMA.NS": "Pharma & Healthcare",
  "ZYDUSLIFE.NS": "Pharma & Healthcare",
  "DRREDDY.NS": "Pharma & Healthcare",
  "LUPIN.NS": "Pharma & Healthcare",
  "BIOCON.NS": "Pharma & Healthcare",
  "DIVISLAB.NS": "Pharma & Healthcare",
  "LAURUSLABS.NS": "Pharma & Healthcare",
  "AUROPHARMA.NS": "Pharma & Healthcare",
  "GLENMARK.NS": "Pharma & Healthcare",
  "ALKEM.NS": "Pharma & Healthcare",
  "TORNTPHARM.NS": "Pharma & Healthcare",
  "APOLLOHOSP.NS": "Pharma & Healthcare",
  "FORTIS.NS": "Pharma & Healthcare",
  "MANKIND.NS": "Pharma & Healthcare",
  "PIIND.NS": "Pharma & Healthcare",
  "MARUTI.NS": "Automobiles",
  "M&M.NS": "Automobiles",
  "BAJAJ-AUTO.NS": "Automobiles",
  "TVSMOTOR.NS": "Automobiles",
  "HEROMOTOCO.NS": "Automobiles",
  "ASHOKLEY.NS": "Automobiles",
  "EICHERMOT.NS": "Automobiles",
  "FORCEMOT.NS": "Automobiles",
  "HYUNDAI.NS": "Automobiles",
  "MOTHERSON.NS": "Automobiles",
  "BOSCHLTD.NS": "Automobiles",
  "BHARATFORG.NS": "Automobiles",
  "SONACOMS.NS": "Automobiles",
  "UNOMINDA.NS": "Automobiles",
  "EXIDEIND.NS": "Automobiles",
  "ITC.NS": "FMCG & Consumer",
  "HINDUNILVR.NS": "FMCG & Consumer",
  "NESTLEIND.NS": "FMCG & Consumer",
  "BRITANNIA.NS": "FMCG & Consumer",
  "DABUR.NS": "FMCG & Consumer",
  "MARICO.NS": "FMCG & Consumer",
  "GODREJCP.NS": "FMCG & Consumer",
  "COLPAL.NS": "FMCG & Consumer",
  "VBL.NS": "FMCG & Consumer",
  "TATACONSUM.NS": "FMCG & Consumer",
  "PATANJALI.NS": "FMCG & Consumer",
  "UNITDSPR.NS": "FMCG & Consumer",
  "GODFRYPHLP.NS": "FMCG & Consumer",
  "PAGEIND.NS": "FMCG & Consumer",
  "DLF.NS": "Real Estate",
  "GODREJPROP.NS": "Real Estate",
  "LODHA.NS": "Real Estate",
  "OBEROIRLTY.NS": "Real Estate",
  "PRESTIGE.NS": "Real Estate",
  "PHOENIXLTD.NS": "Real Estate",
  "ULTRACEMCO.NS": "Cement & Building Mat",
  "SHREECEM.NS": "Cement & Building Mat",
  "AMBUJACEM.NS": "Cement & Building Mat",
  "DALBHARAT.NS": "Cement & Building Mat",
  "GRASIM.NS": "Cement & Building Mat",
  "ASTRAL.NS": "Cement & Building Mat",
  "SUPREMEIND.NS": "Cement & Building Mat",
  "PIDILITIND.NS": "Cement & Building Mat",
  "SRF.NS": "Cement & Building Mat",
  "UPL.NS": "Cement & Building Mat",
  "TITAN.NS": "Consumer Durables",
  "TRENT.NS": "Consumer Durables",
  "ASIANPAINT.NS": "Consumer Durables",
  "HAVELLS.NS": "Consumer Durables",
  "POLYCAB.NS": "Consumer Durables",
  "CGPOWER.NS": "Consumer Durables",
  "VOLTAS.NS": "Consumer Durables",
  "CROMPTON.NS": "Consumer Durables",
  "BLUESTARCO.NS": "Consumer Durables",
  "AMBER.NS": "Consumer Durables",
  "DIXON.NS": "Consumer Durables",
  "KAYNES.NS": "Consumer Durables",
  "KALYANKJIL.NS": "Consumer Durables",
  "DMART.NS": "Consumer Durables",
  "KEI.NS": "Consumer Durables",
  "ABB.NS": "Consumer Durables",
  "SIEMENS.NS": "Consumer Durables",
  "CUMMINSIND.NS": "Consumer Durables",
  "INDIGO.NS": "Travel & Hospitality",
  "INDHOTEL.NS": "Travel & Hospitality",
  "JUBLFOOD.NS": "Travel & Hospitality",
  "VMM.NS": "Miscellaneous",
  "TMPV.NS": "Miscellaneous",
  "PGEL.NS": "Miscellaneous",
  "LTM.NS": "Miscellaneous",
  "SBICARD.NS": "Miscellaneous",
};
